# Config file for GFlows.
# See https://github.com/jbrunton/gflows/wiki/Configuration for options.
githubDir: github-sample
templates:
  engine: ytt
  defaults:
    libs:
      - workflow-configuration/workflows-check
    dependencies:
      - https://raw.githubusercontent.com/CoverGo/ci-workflow-libraries/v0.5/.gflows
